@startuml Auth0
title DcrSecret Endorsement
skinparam shadowing false
skinparam monochrome true
skinparam ParticipantPadding 20
skinparam BoxPadding 10
skinparam MaxMessageSize 10
skinparam SequenceMessageAlignment left

participant "Client" as cli
participant "User-Auth Enclave" as encl
participant "Driver" as driv
participant "DQ Platform" as plat

=== DCR Secret ==
cli<->plat: Authentication
cli->plat: Retrieve DQ pki ""certificate{pkA}""
group Authenticated channel with pkA
cli->encl: ""DcrSecret""
encl<-encl: Compute DcrSecretHash
cli<-encl: ""DcrSecret{DcrSecretHash}/pkA""
end

@enduml