@startuml dq-attestation
skinparam shadowing false
skinparam monochrome true
skinparam ParticipantPadding 20
skinparam BoxPadding 10
' hide footbox

box "Enclave"
participant Worker as worker
participant "Enclave Common" as com
participant "CC API" as ccApi
end box
participant "RoT for Reporting" as rot
participant "Other Enclave" as otherEnc


@enduml